[package]
name = "prodash"
version = "1.1.1"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
description = "A dashboard for visualizing progress of asynchronous and possibly blocking tasks"
edition = "2018"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE.md"]
license = "MIT"
repository = "https://github.com/Byron/crates-io-cli-rs"
readme = "README.md"

[lib]
doctest = true

[features]
default = ["tui-renderer", "log-renderer"]
tui-renderer = ["tui", "tui-react", "termion", "futures-timer", "futures", "unicode-segmentation", "unicode-width", "humantime" ]
log-renderer = ["log"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
dashmap = "3.4.3"
parking_lot = "0.10.0"

# with-logging
log = { version = "0.4.8", optional = true }

# tui-renderer
tui = { version = "0.8.0", optional = true }
tui-react = { version = "0.2.0", optional = true }
termion = { version = "1.5.5", optional = true }
futures-timer = { version = "3.0.1", optional = true }
futures = { version = "0.3.4", optional = true }
unicode-segmentation = { version = "1.6.0", optional = true }
humantime = { version = "2.0.0", optional = true }
unicode-width = { version = "0.1.7", optional = true }

[dev-dependencies]
futures = { version = "0.3.4", features = ["thread-pool"] }
futures-timer = "3.0.1"
rand = "0.7.3"
env_logger = { version = "0.7.1", default-features = false, features = ["termcolor", "atty", "humantime"] }
criterion = "0.3.1"
termion = "1.5.5"
argh = "0.1.3"

[[bench]]
name = "usage"
path = "benches/usage.rs"
harness = false
